spring:
  application:
    name: PrinterSystem
  datasource:
    url: jdbc:mysql://localhost:3306/print_service_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Pubg20061027
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml

sa-token:
  token-name: satoken
  timeout: 2592000
  is-concurrent: true
  is-share: true
  is-read-cookie: false
  isPrint: true
  isLog: true

